# configure for embedded-console

NAME := econ
MAJOR_VERSION := 0
MINOR_VERSION := 0
REVISION := 0
VERSION := $(MAJOR_VERSION).$(MINOR_VERSION).$(REVISION)

PLATFORM ?= quatro55xx

NODEBUG ?= 0

EXTRA_CPPFLAGS ?=
EXTRA_CFLAGS ?=
EXTRA_CXXFLAGS ?=
EXTRA_LDFLAGS ?=
EXTRA_LIBS ?=
